### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by lirantal** [lirantal/dockly#8]
Next milestone:

- [x] Honor the DOCKER_HOST env variable to connect to a specific docker server
- [ ] Searchable containers
- [ ] Show overall containers cpu/memory (dashboard style)
- [ ] Open container/images menu for general commands: remove container/all containers/completely, cleanup images and containers, etc
- [ ] Live logs search for specific string

Refactoring milestone:
- [x] ES6
- [x] Standardjs
- [x] Move to Yarn
- [x] Move to classes for widgets
- [x] Provide framework on-top of blessed for managing widgets (events, init, etc)

**Comment by nileio** [comment]
hi lirantal,
can you use it to connect to a remote docker daemon ? (that is docker is not installed on localhost).. is this the same as Honour Docker_Host env variable milestone ? is this done ?
thanks

**Comment by lirantal** [comment]
@nileio yeah this is already supported.

Just pass the remote connection address in the DOCKER_HOST property, for example:
```
$ DOCKER_HOST=my-remote-docker-domain.com:1234 dockly
```

**Comment by nileio** [comment]
@lirantal can you please clarify . Is this a parameter accepted by dockly ? I can't see there is a parameter to set the docker_host as remote host. I will download and try but if you can clarify that will be great..

**Comment by nileio** [comment]
I realised you meant to add it as an env variable! it works.. the only issue now is that I cant get a remote shell, it just displays a message and exits before I see what it is..

**Comment by lirantal** [comment]
great.
@nileio can you please open a separate issue on the automatic shell thing and let's discuss it there?
